package com.learn.learnviewmodel.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006877)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA2EEFF)
val onPrimaryContainerLight = Color(0xFF004E5A)
val secondaryLight = Color(0xFF4A6268)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE7ED)
val onSecondaryContainerLight = Color(0xFF334A50)
val tertiaryLight = Color(0xFF545D7E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDBE1FF)
val onTertiaryContainerLight = Color(0xFF3D4665)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FAFC)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLight = Color(0xFFF5FAFC)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE4E7)
val onSurfaceVariantLight = Color(0xFF3F484A)
val outlineLight = Color(0xFF6F797B)
val outlineVariantLight = Color(0xFFBFC8CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF83D2E3)
val surfaceDimLight = Color(0xFFD5DBDD)
val surfaceBrightLight = Color(0xFFF5FAFC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EB)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryLightMediumContrast = Color(0xFF003C45)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1B7787)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF223A3F)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF597177)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF2C3553)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF636C8D)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5FAFC)
val onBackgroundLightMediumContrast = Color(0xFF171D1E)
val surfaceLightMediumContrast = Color(0xFFF5FAFC)
val onSurfaceLightMediumContrast = Color(0xFF0C1213)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4E7)
val onSurfaceVariantLightMediumContrast = Color(0xFF2F383A)
val outlineLightMediumContrast = Color(0xFF4B5456)
val outlineVariantLightMediumContrast = Color(0xFF656F71)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F3)
val inversePrimaryLightMediumContrast = Color(0xFF83D2E3)
val surfaceDimLightMediumContrast = Color(0xFFC2C7C9)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFC)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F6)
val surfaceContainerLightMediumContrast = Color(0xFFE3E9EB)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD3D4)

val primaryLightHighContrast = Color(0xFF003139)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00515D)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF183035)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF354D52)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF222B48)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3F4867)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FAFC)
val onBackgroundLightHighContrast = Color(0xFF171D1E)
val surfaceLightHighContrast = Color(0xFFF5FAFC)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDBE4E7)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF252E30)
val outlineVariantLightHighContrast = Color(0xFF424B4D)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF83D2E3)
val surfaceDimLightHighContrast = Color(0xFFB4BABB)
val surfaceBrightLightHighContrast = Color(0xFFF5FAFC)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFECF2F3)
val surfaceContainerLightHighContrast = Color(0xFFDEE3E5)
val surfaceContainerHighLightHighContrast = Color(0xFFD0D5D7)
val surfaceContainerHighestLightHighContrast = Color(0xFFC2C7C9)

val primaryDark = Color(0xFF83D2E3)
val onPrimaryDark = Color(0xFF00363E)
val primaryContainerDark = Color(0xFF004E5A)
val onPrimaryContainerDark = Color(0xFFA2EEFF)
val secondaryDark = Color(0xFFB1CBD1)
val onSecondaryDark = Color(0xFF1C3439)
val secondaryContainerDark = Color(0xFF334A50)
val onSecondaryContainerDark = Color(0xFFCDE7ED)
val tertiaryDark = Color(0xFFBCC5EB)
val onTertiaryDark = Color(0xFF262F4D)
val tertiaryContainerDark = Color(0xFF3D4665)
val onTertiaryContainerDark = Color(0xFFDBE1FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1416)
val onBackgroundDark = Color(0xFFDEE3E5)
val surfaceDark = Color(0xFF0E1416)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF3F484A)
val onSurfaceVariantDark = Color(0xFFBFC8CB)
val outlineDark = Color(0xFF899295)
val outlineVariantDark = Color(0xFF3F484A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF006877)
val surfaceDimDark = Color(0xFF0E1416)
val surfaceBrightDark = Color(0xFF343A3C)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)

val primaryDarkMediumContrast = Color(0xFF99E9FA)
val onPrimaryDarkMediumContrast = Color(0xFF002A31)
val primaryContainerDarkMediumContrast = Color(0xFF4A9CAC)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFC7E1E7)
val onSecondaryDarkMediumContrast = Color(0xFF11292E)
val secondaryContainerDarkMediumContrast = Color(0xFF7C959B)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD3DBFF)
val onTertiaryDarkMediumContrast = Color(0xFF1B2441)
val tertiaryContainerDarkMediumContrast = Color(0xFF878FB3)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1416)
val onBackgroundDarkMediumContrast = Color(0xFFDEE3E5)
val surfaceDarkMediumContrast = Color(0xFF0E1416)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3F484A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD5DEE0)
val outlineDarkMediumContrast = Color(0xFFAAB3B6)
val outlineVariantDarkMediumContrast = Color(0xFF899294)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2C)
val inversePrimaryDarkMediumContrast = Color(0xFF00505B)
val surfaceDimDarkMediumContrast = Color(0xFF0E1416)
val surfaceBrightDarkMediumContrast = Color(0xFF3F4547)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040809)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191F20)
val surfaceContainerDarkMediumContrast = Color(0xFF23292A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3435)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F40)

val primaryDarkHighContrast = Color(0xFFD2F6FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF7FCEDF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000D11)
val secondaryDarkHighContrast = Color(0xFFDBF5FB)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFAEC7CD)
val onSecondaryContainerDarkHighContrast = Color(0xFF000D11)
val tertiaryDarkHighContrast = Color(0xFFEEEFFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB8C1E7)
val onTertiaryContainerDarkHighContrast = Color(0xFF010926)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0E1416)
val onBackgroundDarkHighContrast = Color(0xFFDEE3E5)
val surfaceDarkHighContrast = Color(0xFF0E1416)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F484A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE8F2F4)
val outlineVariantDarkHighContrast = Color(0xFFBBC4C7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF00505B)
val surfaceDimDarkHighContrast = Color(0xFF0E1416)
val surfaceBrightDarkHighContrast = Color(0xFF4B5153)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B2122)
val surfaceContainerDarkHighContrast = Color(0xFF2B3133)
val surfaceContainerHighDarkHighContrast = Color(0xFF363C3E)
val surfaceContainerHighestDarkHighContrast = Color(0xFF424849)














